version: "3"
services:
  web:
    build: .
    ports:
      - "7007:7007"
    volumes:
      - .:/code
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # - ./db:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
  dbadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
volumes:
  db_data: